name: go_app
description: A new Flutter application.

version: 0.1.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: any

  sgf_parser:
    path: ../libs/SGFParser

  goban:
    path: ../libs/Goban


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true